config/routes.rb
Rails.application.routes.draw do
  # namespace :app do
  #   get 'dashboard/index'
  # end
  # namespace :nutritionists do
  #   get 'dashboard/index'
  # end
  devise_for :nutritionists
  devise_for :users
  devise_for :admins
  get 'home/index'
  # get 'shopping_lists/show'
  # get 'allergies/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/shopping_lists/:number', to: 'shopping_lists#show'
  get '/allergies/:number', to: 'allergies#show'

  root to: "home#index"

  namespace :nutritionists do
    root to: 'dashboard#index'
    get '/users/become/:id', to: 'users#become', as: :become_user
  end

  namespace :app do
    root to: 'dashboard#index'
    resources :allergies, only: [:index, :create]
    resources :meal_plans do
      member do
        get :clear
      end
      resources :meals do
        member do
          get :add_ingredient_amount
          get :default
          get :search_ingredient
        end
        resources :ingredient_amounts
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/confirmed_allergy.rb
class ConfirmedAllergy < ApplicationRecord
  belongs_to :user
  belongs_to :allergy
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/ingredient_amount.rb
class IngredientAmount < ApplicationRecord
  belongs_to :meal
  belongs_to :ingredient

  before_validation :verify_fields

  attr_accessor :ingredient_name

  def kcaltotal
    ingredient.kcal * grams.to_i / 100.0 if ingredient
  end

  private
  def verify_fields
    puts self.attributes
    # if ingredient_name.empty?
    #   errors.add(:ingredient_name, 'select existing ingredient or type its name')
    # end
    if grams.nil?
      errors.add(:grams, 'add quantity of the kilocalories')
    else
      if grams.to_f <= 0
        errors.add(:grams, 'value has to be positive number')
      end
    end
    return if errors.any?
    if ingredient_id.nil? && ingredient_name.present?
      self.ingredient_id = Ingredient.create_with_params(ingredient_name).id
    end
  end
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan
  has_many :ingredient_amounts

  def add_random_ingredient_amount
    random_item = [
      {item_name: 'ham', grams: 500, amount: '500 g', category: 'meat'},
      {item_name: 'apples', grams: 700, amount: '3 pieces', category: 'fruit'},
      {item_name: 'milk', grams: 1200, amount: '1200 ml', category: 'dairy'},
      {item_name: 'bread', grams: 200, amount: '200 g', category: 'bread'},
      {item_name: 'carrot', grams: 500, amount: '300 g', category: 'vegetables'},
      {item_name: 'pepper', grams: 10, amount: '10 g', category: 'spices'},
      {item_name: 'trout', grams: 600, amount: '700 g', category: 'fish'},
      {item_name: 'olive oil', grams: 20, amount: '20 g', category: 'other'}
  ].sample
    ingredient = Ingredient.find_or_create_by(name: random_item[:item_name], category: random_item[:category])
    self.ingredient_amounts.create(ingredient: ingredient, grams: random_item[:grams])
  end
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :meals

  def prefill_meals
    if meals.none?
      5.times.each do
        meal = meals.create!

        2.times { meal.add_random_ingredient_amount }
      end
    end
  end

  def clear
    meals.destroy_all
    prefill_meals
  end
end

app/models/nutritionist.rb
class Nutritionist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :confirmed_allergies
  has_many :allergies, through: :confirmed_allergies
  has_many :meal_plans
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  def show
    render json: ['peanuts', 'milks']
  end
end

app/controllers/app/allergies_controller.rb
class App::AllergiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @allergies = Allergy.all
  end

  def create
    current_user.update_attributes(user_params)
    redirect_back fallback_location: app_root_path
  end

  private
  def user_params
    params.require(:user).permit(allergy_ids: [])
  end
end

app/controllers/app/dashboard_controller.rb
class App::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @meal_plan = current_user.meal_plans.find_or_create_by(planned_for: meal_date)
    @meal_plan.prefill_meals
  end

  private

  def meal_date
    params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/controllers/app/meals_controller.rb
class App::MealsController < ApplicationController
  before_action :authenticate_user!

  def add_ingredient_amount
    @meal = Meal.find(params[:id])
    @meal_plan = @meal.meal_plan
    @ingredient_amount = IngredientAmount.new
  end

  def default
    @meal = Meal.find(params[:id])
    @meal_plan = @meal.meal_plan
  end

  def search_ingredient
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html { render layout: false }
      format.js {}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_nutritionist

  def index
  end

  private
  def redirect_nutritionist
    return redirect_to app_root_path if user_signed_in?
    return redirect_to nutritionists_root_path if nutritionist_signed_in?
  end
end

app/controllers/nutritionists/dashboard_controller.rb
class Nutritionists::DashboardController < ApplicationController
  before_action :authenticate_nutritionist!

  def index
    @users = User.all
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def show
    render json: [
      {item_name: 'ham', amount: '500 g', category: 'meat'},
      {item_name: 'apples', amount: '3 pieces', category: 'fruit'},
      {item_name: 'milk', amount: '1200 ml', category: 'dairy'},
      {item_name: 'bread', amount: '200 g', category: 'bread'},
      {item_name: 'carrot', amount: '300 g', category: 'vegetables'},
      {item_name: 'pepper', amount: '10 g', category: 'spices'},
      {item_name: 'trout', amount: '700 g', category: 'fish'},
      {item_name: 'olive oil', amount: '20 g', category: 'other'}
    ]
  end
end

app/helpers/app/dashboard_helper.rb
module App::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nutritionists/dashboard_helper.rb
module Nutritionists::DashboardHelper
end

app/views/app/dashboard/index.html.erb
<hr>

<div class="row">
    <div class="list-group col-4">
        <%= link_to 'Prev', app_root_path(date: @meal_plan.planned_for - 1.day), class: 'list-group-item list-group-item-action list-group-item-secondary' %>
    </div>
    <div class="list-group col-4">
        <%= @meal_plan.planned_for.strftime('%A, %d %B %Y') %>
    </div>
    <div class="list-group col-4">
        <%= link_to 'Next', app_root_path(date: @meal_plan.planned_for + 1.day), class: 'list-group-item list-group-item-action list-group-item-secondary' %>
    </div>
</div>
<div class="row">
    <div class="list-group col-4">

    </div>
    <div class="list-group col-4">
        <%= link_to 'Today', app_root_path, class: 'list-group-item list-group-item-action list-group-item-secondary' %>
    </div>
    <div class="list-group col-4">
        <%= link_to 'Clear', clear_app_meal_plan_path(@meal_plan), class: 'list-group-item list-group-item-action list-group-item-secondary' %>
    </div>
</div>
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <%- @meal_plan.meals.each_with_index do |meal, index| %>
        <a class="list-group-item list-group-item-action <%= 'active' if index === 0 %>" id="list-profile-list" data-toggle="list" href="#list-meal-plan-<%= meal.id %>" role="tab" aria-controls="meal-plan-<%= meal.id %>">
            <h4>#<%= index + 1 %></h4>
        </a>
      <% end %>
      <%# <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Home</a>
      <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Profile</a>
      <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Messages</a>
      <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Settings</a> %>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <%- @meal_plan.meals.each_with_index do |meal, index| %>
        <div class="tab-pane fade show <%= 'active' if index === 0 %>" id="list-meal-plan-<%= meal.id %>" role="tabpanel" aria-labelledby="list-meal-plan-<%= meal.id %>">
            <%= render partial: 'app/meals/meal', locals: { meal_plan: meal.meal_plan, meal: meal} %>
        </div>
      <% end %>
    </div>
  </div>
</div>