config/routes.rb
Rails.application.routes.draw do
  # namespace :app do
  #   get 'dashboard/index'
  # end
  # namespace :nutritionists do
  #   get 'dashboard/index'
  # end
  devise_for :nutritionists
  devise_for :users
  devise_for :admins
  get 'home/index'
  # get 'shopping_lists/show'
  # get 'allergies/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/shopping_lists/:number', to: 'shopping_lists#show'
  get '/allergies/:number', to: 'allergies#show'

  root to: "home#index"

  namespace :nutritionists do
    root to: 'dashboard#index'
    get '/users/become/:id', to: 'users#become', as: :become_user
  end

  namespace :app do
    root to: 'dashboard#index'
    resources :allergies, only: [:index, :create]
    resources :meal_plans do
      member do
        get :clear
      end
      resources :meals do
        member do
          get :add_ingredient_amount
          get :default
          get :search_ingredient
        end
        resources :ingredient_amounts
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/confirmed_allergy.rb
class ConfirmedAllergy < ApplicationRecord
  belongs_to :user
  belongs_to :allergy
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/ingredient_amount.rb
class IngredientAmount < ApplicationRecord
  belongs_to :meal
  belongs_to :ingredient

  before_validation :verify_fields

  attr_accessor :ingredient_name

  def kcaltotal
    ingredient.kcal * grams.to_i / 100.0 if ingredient
  end

  private
  def verify_fields
    puts self.attributes
    # if ingredient_name.empty?
    #   errors.add(:ingredient_name, 'select existing ingredient or type its name')
    # end
    if grams.nil?
      errors.add(:grams, 'add quantity of the kilocalories')
    else
      if grams.to_f <= 0
        errors.add(:grams, 'value has to be positive number')
      end
    end
    return if errors.any?
    if ingredient_id.nil? && ingredient_name.present?
      self.ingredient_id = Ingredient.create_with_params(ingredient_name).id
    end
  end
end

app/models/ingredient_category.rb
class IngredientCategory < ApplicationRecord
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :meal_plan
  has_many :ingredient_amounts

  def add_random_ingredient_amount
    random_item = [
      {item_name: 'ham', grams: 500, amount: '500 g', category: 'meat'},
      {item_name: 'apples', grams: 700, amount: '3 pieces', category: 'fruit'},
      {item_name: 'milk', grams: 1200, amount: '1200 ml', category: 'dairy'},
      {item_name: 'bread', grams: 200, amount: '200 g', category: 'bread'},
      {item_name: 'carrot', grams: 500, amount: '300 g', category: 'vegetables'},
      {item_name: 'pepper', grams: 10, amount: '10 g', category: 'spices'},
      {item_name: 'trout', grams: 600, amount: '700 g', category: 'fish'},
      {item_name: 'olive oil', grams: 20, amount: '20 g', category: 'other'}
  ].sample
    ingredient = Ingredient.find_or_create_by(name: random_item[:item_name], category: random_item[:category])
    self.ingredient_amounts.create(ingredient: ingredient, grams: random_item[:grams])
  end
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :meals

  def prefill_meals
    if meals.none?
      5.times.each do
        meal = meals.create!

        2.times { meal.add_random_ingredient_amount }
      end
    end
  end

  def clear
    meals.destroy_all
    prefill_meals
  end
end

app/models/nutritionist.rb
class Nutritionist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :confirmed_allergies
  has_many :allergies, through: :confirmed_allergies
  has_many :meal_plans
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  def show
    render json: ['peanuts', 'milks']
  end
end

app/controllers/app/meals_controller.rb
class App::MealsController < ApplicationController
  before_action :authenticate_user!

  def add_ingredient_amount
    @meal = Meal.find(params[:id])
    @meal_plan = @meal.meal_plan
    @ingredient_amount = IngredientAmount.new
  end

  def default
    @meal = Meal.find(params[:id])
    @meal_plan = @meal.meal_plan
  end

  def search_ingredient
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html { render layout: false }
      format.js {}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_nutritionist

  def index
  end

  private
  def redirect_nutritionist
    return redirect_to app_root_path if user_signed_in?
    return redirect_to nutritionists_root_path if nutritionist_signed_in?
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def show
    render json: [
      {item_name: 'ham', amount: '500 g', category: 'meat'},
      {item_name: 'apples', amount: '3 pieces', category: 'fruit'},
      {item_name: 'milk', amount: '1200 ml', category: 'dairy'},
      {item_name: 'bread', amount: '200 g', category: 'bread'},
      {item_name: 'carrot', amount: '300 g', category: 'vegetables'},
      {item_name: 'pepper', amount: '10 g', category: 'spices'},
      {item_name: 'trout', amount: '700 g', category: 'fish'},
      {item_name: 'olive oil', amount: '20 g', category: 'other'}
    ]
  end
end

app/helpers/app/dashboard_helper.rb
module App::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="/">Hulk</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <%# <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li> %>
      <%# <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> %>
      <%# <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> %>


      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
          <%- if nutritionist_signed_in? %>
            <%= current_nutritionist.email %>
          <% end %>
          Logged in as
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdown02">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
          </div>
        </li>
      <% elsif nutritionist_signed_in? %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
            Logged in as
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_nutritionist.email %>
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdown03">
            <%= link_to 'Edit profile', edit_nutritionist_registration_path, :class => 'dropdown-item' %> |
            <%= link_to "Logout", destroy_nutritionist_session_path, method: :delete, :class => 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Nutritionists
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdown04">
            <%= link_to "Sign up", new_nutritionist_registration_path, :class => 'dropdown-item' %> |
            <%= link_to "Login", new_nutritionist_session_path, :class => 'dropdown-item' %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
            or
          </a>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %>
        </li>
      <% end %>
    </ul>
      <ul class="navbar-nav justify-content-end">
        <li class="nav-item">
          <%= link_to "Allergies", app_allergies_path, :class => 'nav-link' %>
        </li>
      </ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hulkapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: 'layouts/nav' %>

    <main role="main">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/links.html.erb
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% elsif nutritionist_signed_in? %>
        Logged in as <strong><%= current_nutritionist.email %></strong> nutritionist.
        <%= link_to 'Edit profile', edit_nutritionist_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_nutritionist_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        Nutritionist Area
        <%= link_to "Sign up", new_nutritionist_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_nutritionist_session_path, :class => 'navbar-link'  %>
        User Area
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>